#!/usr/bin/env perl

use autodie;
use Modern::Perl;
use File::Basename;
use Getopt::Long;

my $bucket = "www.treecraft.se";

my $help;
my $sync_world;
my $sync_site;

GetOptions(
    'help|h' => \$help,
    'world' => \$sync_world,
    'site' => \$sync_site,
);

# Fetch path to current directory
my $root = dirname(__FILE__);
my $site = "_site";

if ($help) {
    help();
}

if ($sync_world) {
    say "Syncing world...\n";

    say "Making world.";
    system("$root/make_world");

    sync_site();
    exit;
}

if ($sync_site) {
    sync_site();
}

sub sync {
    my ($dir, $cache, $option) = @_;

    my $header = "";
    $header = "--add-header=\"Cache-Control: $cache\"" if $cache;

    $option = "" unless $option;

    my $cmd = "s3cmd sync $option --acl-public $header $root/$dir s3://$bucket/";

    system("$cmd 2>&1");
}

sub sync_site {
    say "Syncing site...\n";

    # Sync css (cache: 1 week)
    say "Syncing css";
    sync ("$site/css", "max-age=604800", "-m text/css");
    sync ("$site/*.css", "max-age=604800", "-m text/css");

    # Sync rest (cache: 1 hour)
    say "Syncing rest";
    sync ("$site/", "max-age=3600, must-revalidate");

    say "Removing deleted";
    sync ("$site/", "", "--delete-removed");
}

