#!/usr/bin/perl

use autodie;
use Modern::Perl;
use File::Basename;
use Getopt::Long;

my $bucket = "www.treecraft.se";

my $server = "198.24.166.242";
my $world = "treecraft";
my $world_save_dir = "_world";

my $help;
my $sync_world;
my $build;

GetOptions(
    'help|h' => \$help,
    'world' => \$sync_world,
    'build' => \$build,
);

# Fetch path to current directory
my $root = dirname(__FILE__);
my $site = "_site";

if ($help) {
    help();
}

sync_world() if $sync_world;
build() if $build || $sync_world;
sync_site();


sub sync_world {
    say "Syncing world...\n";

    say "Making world.";

    my $clone_dir = "$root/world/";
    mkdir $clone_dir unless -d $clone_dir;

    say "Cloning...";
    system("wget -m \"ftp://$server/$world\" -P $clone_dir -nH 2>&1");
    say("wget -m \"ftp://$server/$world\" -P $clone_dir -nH 2>&1");

    say "Generating world...";
    my $world_dir = "$clone_dir$world";
    my $save_dir = "$root/$world_save_dir";

    system ("overviewer.py $world_dir $save_dir");

    say "Done!";
}

sub build {
    say "Building site...\n";
    system("$root/site build 2>&1");
}

sub sync_site {
    say "Syncing site...\n";

    # Sync css (cache: 1 week)
    say "Syncing css";
    sync ("$site/css", "max-age=604800", "-m text/css");
    sync ("$site/*.css", "max-age=604800", "-m text/css");

    # Sync rest (cache: 1 hour)
    say "Syncing rest";
    sync ("$site/", "max-age=3600, must-revalidate");

    say "Removing deleted";
    sync ("$site/", "", "--delete-removed");
}

sub sync {
    my ($dir, $cache, $option) = @_;

    my $header = "";
    $header = "--add-header=\"Cache-Control: $cache\"" if $cache;

    $option = "" unless $option;

    my $cmd = "s3cmd sync $option --acl-public $header $root/$dir s3://$bucket/";
    system("$cmd 2>&1");
}

